FROM golang:1.24-alpine

# Install build tools and Air for hot reload
RUN apk add --no-cache git \
    && go install github.com/air-verse/air@latest

WORKDIR /app

# Copy Air config
COPY .air.toml .

# Command to run Air
CMD ["air", "-c", ".air.toml"]
